apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-php
  template:
    metadata:
      labels:
        app: tienda-php
    spec:
      containers:
      - name: php
        image: docker.io/eajh954/tiendaropa:f277bb0
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_DATABASE
          value: "tsic2"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-php-service
spec:
  type: NodePort
  selector:
    app: tienda-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085